Add optional html output
mgajda/homplexity pull request #26
Opened 2020-01-20 23:55 UTC by hasufell

This feature can be disabled at compile time, since the
dependencies might be expensive.

The homplexity version and the diagnostic about parsed Modules
is sent to stderr now since it would mess up the html.

Fixes #23

2020-01-21 12:48 UTC, mgajda requested changes
I suggest to reorganize code so that `#ifdef` and `CPP` are needed in only one module.

2020-01-21 12:48 UTC, mgajda commented on app/Homplexity.hs
> +#ifdef HTML_OUTPUT
Elegant way to limit dependencies.
It would be better to move HTML-related code to a different module though.

2020-01-21 12:48 UTC, mgajda commented on lib/Language/Haskell/Homplexity/Message.hs
You might want to move `out` function here, or into separate module.
Anyone who uses `Message` might be also interested in creating outputs :-).

2020-01-21 13:00 UTC, hasufell commented
> I suggest to reorganize code so that `#ifdef` and `CPP` are needed in only one module.

I don't have a clear vision what you are expecting here. IMO, it would only make sense to create `Language.Haskell.Homplexity.Message.HTML`. I don't think it makes sense to change `app/Homplexity.hs`.

2020-01-24 21:40 UTC, mgajda commented
Also, it makes sense to put the version id and headers into HTML so it is apparent which version generated the report.

2020-02-01 00:39 UTC, hasufell commented
Haven't had the time yet. I ran it on a directory of my own project and got:

```
$ homplexity-cli --format=HTML .
Version:  0.4.4.3
Critical:./lib/GHup.hs:SrcLoc "./lib/GHup.hs" 165 1:LambdaCase language extension is not enabled. Please add {-# LANGUAGE LambdaCase #-} pragma at the top of your module.

<html><head><title>Homplexity Analysis.</title></head><style>.warning  .severity { color: orange; }.debug    .severity { color: grey;   }.critical .severity { color: red;    }</style><body></body></html>Critical:./app/Main.hs:SrcLoc "./app/Main.hs" 134 24:RecordWildCards language extension is not enabled. Please add {-# LANGUAGE RecordWildCards #-} pragma at the top of your module.

<html><head><title>Homplexity Analysis.</title></head><style>.warning  .severity { color: orange; }.debug    .severity { color: grey;   }.critical .severity { color: red;    }</style><body></body></html><html><head><title>Homplexity Analysis.</title></head><style>.warning  .severity { color: orange; }.debug    .severity { color: grey;   }.critical .severity { color: red;    }</style><body></body></html><html><head><title>Homplexity Analysis.</title></head><style>.warning  .severity { color: orange; }.debug    .severity { color: grey;   }.critical .severity { color: red;    }</style><body></body></html>Correctly parsed 4 out of 6 input files.
```

So it seems this doesn't work properly across multiple files and I am not sure why there is some completely unformatted text in the beginning.

2020-02-06 10:06 UTC, merged

2020-02-06 10:09 UTC, hasufell commented
Did you figure out what was wrong?